#!/bin/bash
#cd /Users/axelanconaesselmann/Dropbox/WebServer/git/phpFs;
git subtree split --prefix=remote/phpAutoLoader --onto temp_branch --branch temp_branch;
git push -f git@github.com:anconaesselmann/phpAutoLoader.git temp_branch:master;
git branch -D temp_branch;
git push origin master;
cd /Users/axelanconaesselmann/Dropbox/WebServer/git/phpAutoloader;
git pull origin master
#cd /Users/axelanconaesselmann/Dropbox/WebServer/git/phpFs;
